bot:
  discord:
    channels: [bots]
render:
  cfg:
    min: 5
    max: 8
  checkpoints: [
    "diffusion-sdxl-dynavision-0-5-5-7.safetensors",
  ]
  path: /tmp/taleweave-images
  sizes:
    landscape:
      width: 1280
      height: 960
    portrait:
      width: 960
      height: 1280
    square:
      width: 1024
      height: 1024
  steps:
    min: 30
    max: 50
server:
  websocket:
    host: 0.0.0.0
    port: 8001
world:
  size:
    character_items:
      min: 0
      max: 3
    item_effects:
      min: 0
      max: 1
    portals:
      min: 1
      max: 3
    rooms:
      min: 3
      max: 6
    room_characters:
      min: 1
      max: 3
    room_items:
      min: 0
      max: 3
